"""
Mistral-OCR-compatible shim for LibreChat (strategy: mistral_ocr).

LibreChat 0.8.6 only wires mistral_ocr / azure / vertex / document_parser
(custom_ocr is NOT dispatched), so we masquerade as a Mistral OCR endpoint.

Flow LibreChat performs (see packages/api/src/files/mistral/crud.ts):
  POST   {baseURL}/files            multipart purpose=ocr,file=...   -> {"id": ...}
  GET    {baseURL}/files/{id}/url?expiry=24                          -> {"url": ...}
  POST   {baseURL}/ocr  {model, document:{type, document_url|image_url}} -> {"pages":[{"markdown"}]}
  DELETE {baseURL}/files/{id}                                        -> 200

Internally: PDF -> page images (PyMuPDF) -> Qwen vision (LiteLLM, OpenAI-compatible).
Images are sent straight to the vision model.
"""
import os
import re
import io
import base64
import asyncio
import logging
import tempfile
import time
import uuid
from typing import Optional

import fitz  # PyMuPDF
import httpx
from fastapi import FastAPI, UploadFile, File, Form, Header, HTTPException, Request
from fastapi.responses import JSONResponse, Response

logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO"))
log = logging.getLogger("ocr-shim")

# --- Config (all via env) ---------------------------------------------------
LLM_CHAT_URL   = os.environ["LLM_CHAT_URL"]                       # e.g. https://llmproxy.rnd-ai.rn-t.ru/v1/chat/completions
LLM_API_KEY    = os.environ.get("LLM_API_KEY", "")               # LiteLLM key
VISION_MODEL   = os.environ.get("VISION_MODEL", "qwen-3.6-thinking")
SELF_BASE_URL  = os.environ.get("SELF_BASE_URL", "http://ocr-shim:8000")
SHARED_SECRET  = os.environ.get("OCR_SHARED_SECRET", "")         # optional: must match LibreChat OCR_API_KEY
CA_CERT        = os.environ.get("CA_CERT", "")                   # path to internal CA bundle for LiteLLM TLS
OCR_DPI        = int(os.environ.get("OCR_DPI", "200"))
CONCURRENCY    = max(1, int(os.environ.get("CONCURRENCY", "4")))
DOCUMENT_CONCURRENCY = max(1, int(os.environ.get("DOCUMENT_CONCURRENCY", "1")))
MAX_TOKENS     = int(os.environ.get("OCR_MAX_TOKENS", "4096"))
HTTP_TIMEOUT   = float(os.environ.get("LLM_TIMEOUT", "180"))

OCR_PROMPT = os.environ.get(
    "OCR_PROMPT",
    "Извлеки весь текст с этого изображения документа дословно, сохраняя порядок строк, "
    "таблицы (в виде markdown-таблиц) и структуру. Не добавляй комментариев, пояснений или "
    "заголовков — только сам распознанный текст в формате markdown. Если на изображении нет "
    "текста, верни пустую строку.",
)

STORE = tempfile.gettempdir()
_verify = CA_CERT if CA_CERT and os.path.exists(CA_CERT) else True

app = FastAPI(title="LibreChat OCR shim", version="1.0")
DOCUMENT_SEM = asyncio.Semaphore(DOCUMENT_CONCURRENCY)


def _check_auth(authorization: Optional[str]):
    if not SHARED_SECRET:
        return
    expected = f"Bearer {SHARED_SECRET}"
    if authorization != expected:
        raise HTTPException(status_code=401, detail="invalid OCR credentials")


def _path(file_id: str) -> str:
    # file_id is generated by us; keep it filesystem-safe
    safe = re.sub(r"[^A-Za-z0-9_.-]", "", file_id)
    return os.path.join(STORE, f"ocrshim-{safe}")


# --- 1) upload --------------------------------------------------------------
@app.post("/files")
async def upload_file(
    file: UploadFile = File(...),
    purpose: str = Form("ocr"),
    authorization: Optional[str] = Header(None),
):
    _check_auth(authorization)
    file_id = uuid.uuid4().hex
    data = await file.read()
    with open(_path(file_id), "wb") as f:
        f.write(data)
    # also remember original filename/mime for type detection
    with open(_path(file_id) + ".meta", "w") as f:
        f.write((file.filename or "") + "\n" + (file.content_type or ""))
    log.info("stored file %s (%s, %d bytes)", file_id, file.filename, len(data))
    return {"id": file_id, "object": "file", "bytes": len(data), "purpose": purpose}


# --- 2) signed url (we just hand back a self-URL carrying the id) -----------
@app.get("/files/{file_id}/url")
async def signed_url(file_id: str, expiry: int = 24, authorization: Optional[str] = Header(None)):
    _check_auth(authorization)
    if not os.path.exists(_path(file_id)):
        raise HTTPException(status_code=404, detail="file not found")
    return {"url": f"{SELF_BASE_URL}/files/{file_id}/raw"}


# --- raw fetch (not strictly needed by LibreChat, but keeps the URL real) ---
@app.get("/files/{file_id}/raw")
async def raw_file(file_id: str):
    p = _path(file_id)
    if not os.path.exists(p):
        raise HTTPException(status_code=404, detail="file not found")
    return Response(content=open(p, "rb").read(), media_type="application/octet-stream")


# --- 3) OCR -----------------------------------------------------------------
def _extract_id(url: str) -> str:
    m = re.search(r"/files/([A-Za-z0-9_.-]+)/raw", url or "")
    if not m:
        raise HTTPException(status_code=400, detail=f"cannot parse file id from url: {url}")
    return m.group(1)


def _is_pdf(file_id: str) -> bool:
    meta = _path(file_id) + ".meta"
    name = ctype = ""
    if os.path.exists(meta):
        parts = open(meta).read().split("\n")
        name = parts[0] if parts else ""
        ctype = parts[1] if len(parts) > 1 else ""
    if "pdf" in ctype.lower() or name.lower().endswith(".pdf"):
        return True
    # sniff magic bytes
    with open(_path(file_id), "rb") as f:
        return f.read(5) == b"%PDF-"


def _rasterize(file_id: str) -> list[bytes]:
    """Return a list of PNG bytes, one per page (or the single image as-is)."""
    p = _path(file_id)
    if _is_pdf(file_id):
        pages = []
        zoom = OCR_DPI / 72.0
        mat = fitz.Matrix(zoom, zoom)
        with fitz.open(p) as doc:
            for page in doc:
                pix = page.get_pixmap(matrix=mat, alpha=False)
                pages.append(pix.tobytes("png"))
        return pages
    # already an image
    return [open(p, "rb").read()]


async def _ocr_page(
    client: httpx.AsyncClient,
    png: bytes,
    sem: asyncio.Semaphore,
    page_index: int,
    total_pages: int,
    progress: dict[str, int],
    progress_lock: asyncio.Lock,
) -> str:
    b64 = base64.b64encode(png).decode()
    payload = {
        "model": VISION_MODEL,
        "temperature": 0,
        "max_tokens": MAX_TOKENS,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": OCR_PROMPT},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                ],
            }
        ],
    }
    headers = {"Content-Type": "application/json"}
    if LLM_API_KEY:
        headers["Authorization"] = f"Bearer {LLM_API_KEY}"
    async with sem:
        start = time.perf_counter()
        log.info("OCR page %d/%d: started", page_index + 1, total_pages)
        r = await client.post(LLM_CHAT_URL, json=payload, headers=headers, timeout=HTTP_TIMEOUT)
        log.info(
            "OCR page %d/%d: completed in %.1fs",
            page_index + 1,
            total_pages,
            time.perf_counter() - start,
        )
        async with progress_lock:
            progress["completed"] += 1
            completed = progress["completed"]
            percent = completed * 100 / total_pages
        log.info("OCR progress: %d/%d pages completed (%.1f%%)", completed, total_pages, percent)
    r.raise_for_status()
    data = r.json()
    try:
        return data["choices"][0]["message"]["content"] or ""
    except (KeyError, IndexError, TypeError):
        log.warning("unexpected LLM response: %s", data)
        return ""


@app.post("/ocr")
async def ocr(request: Request, authorization: Optional[str] = Header(None)):
    _check_auth(authorization)
    body = await request.json()
    doc = body.get("document", {})
    url = doc.get("document_url") or doc.get("image_url")
    file_id = _extract_id(url)
    if not os.path.exists(_path(file_id)):
        raise HTTPException(status_code=404, detail="file not found")

    if DOCUMENT_SEM.locked():
        log.info(
            "OCR file %s: waiting for document slot, document_concurrency=%d",
            file_id,
            DOCUMENT_CONCURRENCY,
        )
    async with DOCUMENT_SEM:
        document_start = time.perf_counter()
        images = _rasterize(file_id)
        log.info(
            "OCR file %s: %d page(s) via %s, document_concurrency=%d, page_concurrency=%d",
            file_id,
            len(images),
            VISION_MODEL,
            DOCUMENT_CONCURRENCY,
            CONCURRENCY,
        )

        sem = asyncio.Semaphore(CONCURRENCY)
        progress = {"completed": 0}
        progress_lock = asyncio.Lock()
        limits = httpx.Limits(max_connections=CONCURRENCY, max_keepalive_connections=CONCURRENCY)
        async with httpx.AsyncClient(verify=_verify, limits=limits) as client:
            texts = await asyncio.gather(
                *[
                    _ocr_page(client, img, sem, page_index, len(images), progress, progress_lock)
                    for page_index, img in enumerate(images)
                ]
            )
        log.info(
            "OCR file %s: completed %d page(s) in %.1fs",
            file_id,
            len(images),
            time.perf_counter() - document_start,
        )

    pages = [{"index": i, "markdown": t, "images": [], "dimensions": None} for i, t in enumerate(texts)]
    return JSONResponse({"pages": pages, "model": VISION_MODEL, "usage_info": {"pages_processed": len(pages)}})


# --- 4) cleanup -------------------------------------------------------------
@app.delete("/files/{file_id}")
async def delete_file(file_id: str, authorization: Optional[str] = Header(None)):
    _check_auth(authorization)
    for suffix in ("", ".meta"):
        try:
            os.remove(_path(file_id) + suffix)
        except FileNotFoundError:
            pass
    return {"id": file_id, "deleted": True}


@app.get("/health")
async def health():
    return {"status": "ok"}
